/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class Operacion_nodo extends javax.swing.JFrame {

    /**
     * Creates new form Operacion_nodo
     */
    public Operacion_nodo() {
        super("Operación de Lista Enlazada");
        initComponents();
        Mostrar_nodo.setEditable(false);
        eliminar.setEnabled(false);
        Indicar_n.setEditable(false);
        Mostrar_n.setEnabled(false);
        Mostrar_herramienta.setEditable(false);
        Mcantidad.setEditable(false);
        Minversion.setEditable(false);
        Mconcatenar.setEditable(false);
        Mminuscula.setEditable(false);
    }
    
    Listaenlaza lista_intento = new Listaenlaza();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresopalabra = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mostrar_nodo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Indicar_n = new javax.swing.JTextField();
        Mostrar_n = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Mostrar_herramienta = new javax.swing.JTextField();
        Mcantidad = new javax.swing.JTextField();
        Minversion = new javax.swing.JTextField();
        Mconcatenar = new javax.swing.JTextField();
        Mminuscula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar datos para cada nodo:");

        agregar.setBackground(new java.awt.Color(255, 255, 255));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenIcono/ingresar.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Lista Enlazada Actual");

        Mostrar_nodo.setColumns(20);
        Mostrar_nodo.setRows(5);
        jScrollPane1.setViewportView(Mostrar_nodo);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenIcono/node2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Index");

        Indicar_n.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Indicar_nFocusGained(evt);
            }
        });
        Indicar_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Indicar_nKeyTyped(evt);
            }
        });

        Mostrar_n.setBackground(new java.awt.Color(255, 255, 255));
        Mostrar_n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenIcono/botoninicar2.png"))); // NOI18N
        Mostrar_n.setText("Mostrar");
        Mostrar_n.setBorder(null);
        Mostrar_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_nActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenIcono/cancel.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setBorder(null);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Index Elegido fue:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad de digito:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Inversión:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Concatenar:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Minúscula:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ingresopalabra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agregar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Mostrar_herramienta)
                                            .addComponent(Mcantidad)
                                            .addComponent(Minversion)
                                            .addComponent(Mconcatenar)
                                            .addComponent(Mminuscula, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)))
                                    .addComponent(Indicar_n))
                                .addGap(18, 18, 18)
                                .addComponent(Mostrar_n)
                                .addGap(47, 47, 47)
                                .addComponent(eliminar)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresopalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Indicar_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mostrar_n)
                    .addComponent(eliminar))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Mostrar_herramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Mcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Minversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Mconcatenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Mminuscula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String texto = ingresopalabra.getText();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usted no ha ingresado nada dato para nodo");
        }else{
            lista_intento.agregando(texto);
            Mostrar_nodo.setText(null);
            for (int i = 0; i < lista_intento.size; i++) {
                Mostrar_nodo.setText(Mostrar_nodo.getText()+ lista_intento.obtener(i).toString() +"       ");
            }
            ingresopalabra.setText(null);
            Indicar_n.setEditable(true);
            eliminar.setEnabled(true);
            Mostrar_n.setEnabled(true);
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        String index_indicado = Indicar_n.getText();
        if (index_indicado.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debe indicar el numero para el elemento de index");
        }else{
            int tras_index = Integer.parseInt(index_indicado);
            if (tras_index > lista_intento.size) {
                JOptionPane.showMessageDialog(null, "La cantidad de index no puede ser mayor la cantidad de lista enlazada, por favor ingresar el valor de nuevo");
            }else{
                if (lista_intento.cabeza == null) {
                    Mostrar_nodo.setText("Ya no hay mas elemento para eliminar");
                }else if (lista_intento.size == 1 && tras_index == 1) {
                    JOptionPane.showMessageDialog(null, "Si desea eliminar el primer elemento, debe colocar el numero 0");
                }else{
                    Mostrar_nodo.setText(null);
                    lista_intento.eliminar(tras_index);
                    for (int i = 0; i < lista_intento.size; i++) {
                    Mostrar_nodo.setText(Mostrar_nodo.getText()+ lista_intento.obtener(i).toString() +"  ");
                    }
                }                    
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void Mostrar_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_nActionPerformed
        String index_indicado = Indicar_n.getText();
        
        int cantidadLetras = 0;
        
        String cadenaInvertida = "";
        
        int ultima = 0;
        
        ultima = lista_intento.size();
        
        if (index_indicado.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debe indicar el numero para el elemento de index");
        }else{
            int tras_index = Integer.parseInt(index_indicado);
            if (tras_index>lista_intento.size) {
                JOptionPane.showMessageDialog(null,"Esta fuera de tamaño de la lista, por favor, ingresar de nuevo para mostrar");
            }else{
                Mostrar_herramienta.setText(lista_intento.obtener(tras_index).toString()); //Parte de mostrar el index elegido
                String aux = lista_intento.obtener(tras_index).toString();
                for (char c: aux.toCharArray()) {
                    cantidadLetras++;
                }
                Mcantidad.setText("La cadena de texto tiene " + cantidadLetras + " letras."); //Parte de mostrar la cantidad de digitos
                
                for (int j = aux.length() - 1; j >= 0; j--) {
                    cadenaInvertida += aux.charAt(j);
                }
                Minversion.setText(cadenaInvertida); //Parte de mostrar la cadena invertida
                
                Mconcatenar.setText(lista_intento.obtener(tras_index).toString());
                String ultimapalabra = lista_intento.obtener(ultima-1).toString();
                Mconcatenar.setText(Mconcatenar.getText() + "  " + ultimapalabra); //Parte de mostrar la concatenar con la ultima palabra
                
                String word = lista_intento.obtener(tras_index).toString().toLowerCase();
                Mminuscula.setText(word); //Parte de mostrar la minuscula para index elegido
            }
        }
        
    }//GEN-LAST:event_Mostrar_nActionPerformed

    private void Indicar_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Indicar_nKeyTyped
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_Indicar_nKeyTyped

    private void Indicar_nFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Indicar_nFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Indicar_nFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Indicar_n;
    private javax.swing.JTextField Mcantidad;
    private javax.swing.JTextField Mconcatenar;
    private javax.swing.JTextField Minversion;
    private javax.swing.JTextField Mminuscula;
    private javax.swing.JTextField Mostrar_herramienta;
    private javax.swing.JButton Mostrar_n;
    private javax.swing.JTextArea Mostrar_nodo;
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField ingresopalabra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
